# Generated by Django 5.1.1 on 2024-09-30 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_game', 'In Game'), ('busy', 'Busy')], default='offline', max_length=20)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_42', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('avatar', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_game', 'In Game'), ('busy', 'Busy')], default='offline', max_length=20)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_42', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
