# Generated by Django 5.1.1 on 2024-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiuser_friends_apiuser_friends_wait_user_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='friends_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
