# Generated by Django 5.1.1 on 2024-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apiuser_id_alter_apiuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
