# Generated by Django 5.1.1 on 2024-10-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apiuser_friends_request_user_friends_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
