# Generated by Django 5.1.1 on 2024-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiuser_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='avatar_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
