# Generated by Django 5.1.1 on 2024-09-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_name_apiuser_avatar_apiuser_session_42_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
