# Generated by Django 5.1.1 on 2024-10-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_apiuser_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='session_42',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='two_factor_auth',
        ),
    ]
