# Generated by Django 5.1.1 on 2024-10-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_apiuser_age_remove_apiuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_42',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth',
        ),
    ]
