# Generated by Django 5.1.1 on 2024-09-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_apiuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
