# Generated by Django 5.1.1 on 2024-09-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_apiuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='avatar',
        ),
    ]
